CREATE TABLE AUTOR ( ID_AUTOR INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE VARCHAR(50) NOT NULL, NACIONALIDAD VARCHAR(25) );

CREATE TABLE LIBRO ( ID_LIBRO INTEGER PRIMARY KEY AUTOINCREMENT, TITULO VARCHAR(50) NOT NULL, 
NUM_PAGINAS INT, ANIO_EDIC INT, ID_AUTOR INT, FOREIGN KEY(ID_AUTOR) REFERENCES AUTOR (ID_AUTOR));